# Generated by Django 4.1.3 on 2022-11-15 07:00

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=True, max_length=100)),
                ('product_image', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image')),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
