# Generated by Django 4.1.3 on 2022-11-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='product_title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
