# Generated by Django 4.1.3 on 2022-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_category_subcategory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_off',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
