# Generated by Django 4.1.3 on 2022-11-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_product_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_old_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
