# Generated by Django 4.1.3 on 2022-11-16 06:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
    ]
