# Generated by Django 4.1.3 on 2022-11-16 07:00

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_product_ppoi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=versatileimagefield.fields.VersatileImageField(default=True, upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=versatileimagefield.fields.VersatileImageField(default=True, upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=versatileimagefield.fields.VersatileImageField(default=True, upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
    ]
