# Generated by Django 4.1.3 on 2022-11-16 07:02

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_product_image_product_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
    ]
