# Generated by Django 4.1.3 on 2022-11-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_product_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maintenance',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
