# Generated by Django 4.1.3 on 2022-11-17 08:31

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_product_maintenance_product_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/testimagemodel/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.cart')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='web.product'),
        ),
    ]
