# Generated by Django 4.1.3 on 2022-11-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_cart_alter_product_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
