# Generated by Django 4.1.3 on 2022-11-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rename_order_address_order_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
