# Generated by Django 4.1.3 on 2022-11-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.CharField(max_length=10),
        ),
    ]
