# Generated by Django 4.1.3 on 2022-11-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_order_phone1_alter_order_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.filterprice'),
        ),
    ]
